name: Release to PyPI

on:
  push:
    tags:
      - 'v\d+.\d+.\d+'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build package
        run: python -m build

      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload wheels to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GIT_TOKEN }}
          file: dist/retroapi-${{ github.ref_name }}-py3-none-any.whl
          tag: ${{ github.ref }}
          overwrite: true
          body: "Retro API"
