name: Release to PyPI

on:
  push:
    tags: [v\d+\.\d+\.\d+]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read release.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat ./.github/release.md)                  
          r="${r//'%'/'%25'}"                         
          r="${r//$'\n'/'%0A'}"                      
          r="${r//$'\r'/'%0D'}"                     
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build package
        run: python -m build

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload wheels to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GIT_TOKEN }}
          file: dist/retroapi*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}
